spring:
  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest
    
employee:
  rabbitmq:
    exchange: employee.exchange
    queue: employee.queue
    routingkey: employee.routingkey